In [1]:
#import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.cross_validation import train_test_split

C:\Users\venu\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
dataset=pd.read_csv('machine_readable.csv')

In [3]:
dataset.columns

Index(['Series_reference', 'Period', 'Type', 'Data_value', 'Lower_CI',
       'Upper_CI', 'Units', 'Indicator', 'Cause', 'Validation', 'Population',
       'Age', 'Severity'],
      dtype='object')

In [4]:
dataset.isnull().sum()

Series_reference    0
Period              0
Type                5
Data_value          3
Lower_CI            2
Upper_CI            1
Units               2
Indicator           0
Cause               1
Validation          0
Population          0
Age                 0
Severity            0
dtype: int64

In [5]:
dataset.dtypes

Series_reference     object
Period               object
Type                 object
Data_value          float64
Lower_CI            float64
Upper_CI            float64
Units                object
Indicator            object
Cause                object
Validation           object
Population           object
Age                  object
Severity             object
dtype: object

In [6]:
#dataset.Type.mode()
dataset.Type.fillna(dataset.Type.mode().values[0],inplace=True)

In [7]:
dataset.Type.isnull().sum()

0

In [8]:
dataset.Data_value.fillna(dataset.Data_value.mean(),inplace=True)

In [9]:
dataset.Data_value.isnull().sum()

0

In [10]:
dataset.Lower_CI.fillna(dataset.Lower_CI.mean(),inplace=True)

In [11]:
dataset.Data_value.isnull().sum()

0

In [12]:
dataset.Upper_CI.fillna(dataset.Upper_CI.mean(),inplace=True)

In [13]:
dataset.isnull().sum()

Series_reference    0
Period              0
Type                0
Data_value          0
Lower_CI            0
Upper_CI            0
Units               2
Indicator           0
Cause               1
Validation          0
Population          0
Age                 0
Severity            0
dtype: int64

In [14]:
dataset.Units.fillna(dataset.Units.mode().values[0],inplace=True)

In [15]:
dataset.Cause.fillna(dataset.Cause.mode().values[0],inplace=True)

In [16]:
dataset.isnull().sum()

Series_reference    0
Period              0
Type                0
Data_value          0
Lower_CI            0
Upper_CI            0
Units               0
Indicator           0
Cause               0
Validation          0
Population          0
Age                 0
Severity            0
dtype: int64

In [17]:
dataset.pop('Series_reference')

0        W_A11
1        W_A11
2        W_A11
3        W_A11
4        W_A11
5        W_A11
6        W_A11
7        W_A11
8        W_A11
9        W_A11
10       W_A11
11       W_A11
12       W_A11
13       W_A11
14       W_A12
15       W_A12
16       W_A12
17       W_A12
18       W_A12
19       W_A12
20       W_A12
21       W_A12
22       W_A12
23       W_A12
24       W_A12
25       W_A12
26       W_A12
27       W_A12
28      W_F11B
29      W_F11B
         ...
2286       p22
2287       p22
2288       p22
2289       p22
2290       p22
2291       p22
2292       p22
2293       p22
2294       p22
2295       p22
2296       p22
2297       p22
2298       p22
2299       p22
2300       p21
2301       p21
2302       p21
2303       p21
2304       p21
2305       p21
2306       p21
2307       p21
2308       p21
2309       p21
2310       p21
2311       p21
2312       p21
2313       p21
2314       p21
2315       p21
Name: Series_reference, Length: 2316, dtype: object

In [18]:
dataset.pop('Period')

0       2000-02
1       2001-03
2       2002-04
3       2003-05
4       2004-06
5       2005-07
6       2006-08
7       2007-09
8       2008-10
9       2009-11
10      2010-12
11      2011-13
12      2012-14
13      2013-15
14      2000-02
15      2001-03
16      2002-04
17      2003-05
18      2004-06
19      2005-07
20      2006-08
21      2007-09
22      2008-10
23      2009-11
24      2010-12
25      2011-13
26      2012-14
27      2013-15
28      2000-02
29      2001-03
         ...
2286       2002
2287       2003
2288       2004
2289       2005
2290       2006
2291       2007
2292       2008
2293       2009
2294       2010
2295       2011
2296       2012
2297       2013
2298       2014
2299       2015
2300       2000
2301       2001
2302       2002
2303       2003
2304       2004
2305       2005
2306       2006
2307       2007
2308       2008
2309       2009
2310       2010
2311       2011
2312       2012
2313       2013
2314       2014
2315       2015
Name: Period, Length: 2316, dtype: object

In [19]:
dataset

,Type,Data_value,Lower_CI,Upper_CI,Units,Indicator,Cause,Validation,Population,Age,Severity
0,Moving average,59.666667,50.925823,68.407510,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
1,Moving average,60.000000,51.234775,68.765225,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
2,Moving average,59.000000,50.308125,67.691875,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
3,Moving average,59.000000,50.308125,67.691875,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
4,Moving average,61.333333,52.471252,70.195415,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
5,Moving average,63.000000,54.018317,71.981683,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
6,Moving average,57.333333,48.765104,65.901562,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
7,Moving average,63.666667,54.637586,72.695747,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
8,Moving average,64.000000,54.947314,73.052686,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
9,Moving average,64.333333,55.257103,73.409563,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
10,Moving average,55.333333,46.915877,63.750790,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
11,Moving average,54.333333,45.992285,62.674382,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
12,Moving average,51.333333,43.225829,59.440838,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
13,Moving average,52.000000,43.840019,60.159981,Injuries,Number,Assault,Validated,Whole pop,All ages,Fatal
14,Moving average,1.543343,1.317063,1.769623,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
15,Moving average,1.525510,1.302606,1.748415,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
16,Moving average,1.464856,1.249053,1.680658,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
17,Moving average,1.444340,1.231539,1.657142,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
18,Moving average,1.488137,1.273033,1.703241,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
19,Moving average,1.508693,1.293405,1.723980,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
20,Moving average,1.356025,1.153072,1.558977,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
21,Moving average,1.504095,1.290342,1.717847,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
22,Moving average,1.503080,1.289763,1.716397,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
23,Moving average,1.491112,1.279822,1.702402,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
24,Moving average,1.259846,1.067084,1.452608,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
25,Moving average,1.238244,1.046780,1.429708,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
26,Moving average,1.166252,0.980343,1.352161,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
27,Moving average,1.154224,0.971323,1.337126,"Per 100,000 people",Age-standardised rate,Assault,Validated,Whole pop,All ages,Fatal
28,Moving average,64.333333,55.257103,73.409563,Injuries,Number,Falls,Validated,Whole pop,0-74 years,Fatal
29,Moving average,68.666667,59.289742,78.043592,Injuries,Number,Falls,Validated,Whole pop,0-74 years,Fatal
...,...,...,...,...,...,...,...,...,...,...,...
2286,Single year,7.472556,5.669725,9.275387,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2287,Single year,7.306819,5.530505,9.083133,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2288,Single year,5.162211,3.670408,6.654015,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2289,Single year,6.524486,4.845337,8.203636,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2290,Single year,6.439670,4.767846,8.111493,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2291,Single year,5.725688,4.153775,7.297602,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2292,Single year,3.849905,2.555108,5.144703,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2293,Single year,4.596589,3.187838,6.005340,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2294,Single year,5.383682,3.858568,6.908796,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2295,Single year,4.329554,2.967996,5.691112,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2296,Single year,3.558841,2.323312,4.794370,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2297,Single year,4.126542,2.794529,5.458555,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2298,Single year,5.096044,3.621000,6.571088,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2299,Single year,4.426406,3.069184,5.783628,"Per 100,000 people",Age-standardised rate,Pedestrian,Validated,Children,0-14 years,Serious
2300,Single year,78.000000,60.690067,95.309933,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2301,Single year,62.000000,46.567228,77.432772,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2302,Single year,66.000000,50.077177,81.922823,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2303,Single year,65.000000,49.198265,80.801735,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2304,Single year,46.000000,32.706878,59.293122,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2305,Single year,58.000000,43.073359,72.926641,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2306,Single year,57.000000,42.202596,71.797404,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2307,Single year,51.000000,37.003057,64.996943,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2308,Single year,34.000000,22.571544,45.428456,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2309,Single year,41.000000,28.450107,53.549893,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2310,Single year,48.000000,34.420971,61.579029,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2311,Single year,39.000000,26.760029,51.239971,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2312,Single year,32.000000,20.912769,43.087231,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2313,Single year,37.000000,25.078005,48.921995,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2314,Single year,46.000000,32.706878,59.293122,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious
2315,Single year,41.000000,28.450107,53.549893,Injuries,Number,Pedestrian,Validated,Children,0-14 years,Serious

In [20]:
dataset=dataset.apply(LabelEncoder().fit_transform)
dataset.head()

,Type,Data_value,Lower_CI,Upper_CI,Units,Indicator,Cause,Validation,Population,Age,Severity
0,0,1000,1018,1017,0,1,1,1,2,3,0
1,0,1001,1020,1018,0,1,1,1,2,3,0
2,0,996,1014,1014,0,1,1,1,2,3,0
3,0,996,1014,1014,0,1,1,1,2,3,0
4,0,1004,1025,1023,0,1,1,1,2,3,0

In [21]:
print(dataset.Type.value_counts())
print(" ")
print(dataset.Units.value_counts())
print(" ")
print(dataset.Indicator.value_counts())
print(" ")
print(dataset.Cause.value_counts())
print(" ")
print(dataset.Validation.value_counts())
print(" ")
print(dataset.Population.value_counts())
print(" ")
print(dataset.Age.value_counts())
print(" ")

1    1949
0     367
Name: Type, dtype: int64

0    1128
2    1066
1      60
3      31
4      31
Name: Units, dtype: int64

1    1127
0    1127
3      31
2      31
Name: Indicator, dtype: int64

4    624
7    426
0    300
1    256
6    210
9    184
5    128
3     68
8     60
2     60
Name: Cause, dtype: int64

1    2194
0     122
Name: Validation, dtype: int64

2    1064
1     684
0     568
Name: Population, dtype: int64

3    1324
0     568
2     228
1     196
Name: Age, dtype: int64

In [22]:
#sns.pairplot(dataset,hue='Severity')
y=dataset.pop('Severity')
X=dataset

In [23]:
X=pd.get_dummies(dataset,columns=['Indicator'])

In [24]:
X.shape

(2316, 13)

In [25]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [28]:
from sklearn.tree import DecisionTreeClassifier
D=DecisionTreeClassifier()
D.fit(X_train,Y_train)
pred=D.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,pred)

0.8146551724137931